### ISSUE TITLE
suspend board and wakeup from push button PCIexpress issue

### ISSUE THREAD

**Issue by simon0356** [Gateworks/linux-imx6#1]
Hi

I have a gateworks GW5111-D using following linux version : 
root@gateworks:~# uname -a
Linux gateworks 3.14.48-01713-gcff6aca #2124 SMP Thu Dec 17 11:42:40 PST 2015 armv7l GNU/Linux

And GSC version 47

I set my system on mSata SSD 

I try to wake up my board after a systemctl suspend with the push button 
The PCIe bus issue an error after waking up : 

root@gateworks:~# systemctl suspend
[  906.495352] PM: Syncing filesystems ... done.
[  906.504141] Freezing user space processes ... (elapsed 0.001 seconds) done.
[  906.512507] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
[  906.522853] sd 0:0:0:0: [sda] Synchronizing SCSI cache
[  906.528114] sd 0:0:0:0: [sda] Stopping disk
[  906.621648] PM: suspend of devices complete after 99.919 msecs
[  906.627488] PM: suspend devices took 0.100 seconds
[  906.632734] PM: late suspend of devices complete after 0.426 msecs
[  906.794295] PM: noirq suspend of devices complete after 155.371 msecs
[  906.800756] Disabling non-boot CPUs ...
[  906.805171] CPU1: shutdown
[  906.809035] CPU2: shutdown
[  906.812686] CPU3: shutdown
[  906.816039] Enabling non-boot CPUs ...
[  906.820274] CPU1: Booted secondary processor
[  906.820540] CPU1 is up
[  906.827637] CPU2: Booted secondary processor
[  906.827840] CPU2 is up
[  906.834954] CPU3: Booted secondary processor
[  906.835178] CPU3 is up
[  906.847291] imx6q-pcie 1ffc000.pcie: transition to gen2 is stuck, reset PHY!
[  906.866750] pcieport 0000:01:00.0: Refused to change power state, currently in D3
[  907.030970] PM: noirq resume of devices complete after 189.110 msecs
[  907.038025] PM: early resume of devices complete after 0.508 msecs
[  907.045246] gpmi-nand 112000.gpmi-nand: enable the asynchronous EDO mode 5

Have you some advise for me ?

Thanks

Simon

**Comment by rerbstoesser** [comment]
Hello Simon, we would be happy to work with you on this. We don't have the GW5111 as a product, but please email us at support@gateworks.com and we can discuss more! 

Best Regards,
Ryan

**Comment by simon0356** [comment]
Hello 
I made a mistake my product is a GW5411-D, i will re-send a mail to support@gateworks.com.

Thanks

**Comment by simon0356** [comment]
Hello,

I have send the mail yesterday and  already send a mail one week ago and still have no response, could you please give me your email address ? 

Thanks

**Comment by rerbstoesser** [comment]
Hello Simon, our email is support@gateworks.com

Please provide the email address you are using so we can be sure it has not been filtered and we can search for it.

We look forward to helping you!

Best Regards,
Ryan

**Comment by simon0356** [comment]
I have use simon.tropee at yogoko.fr

Thanks 
Simon
